disable_snapshots()
analytics_settings(enable=False)
allow_k8s_contexts(os.getenv("TILT_ALLOW_CONTEXT"))

k8s_yaml('kubernetes.yaml')

docker_build('service-a-image', './image-a', build_args={'ECHO': 'a'})
docker_build('service-b-image', './image-b', target='http')

k8s_yaml('verify-a.yaml')
k8s_yaml('verify-b.yaml')

k8s_resource('verify-a', resource_deps=['service-a'])
k8s_resource('verify-b', resource_deps=['service-b'])
