apiVersion: v1
kind: Service
metadata:
  name: wedding
spec:
  selector:
    app: wedding
  ports:
    - name: wedding
      port: 2376
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wedding
  labels:
    app: wedding
spec:
  selector:
    matchLabels:
      app: wedding
  template:
    metadata:
      labels:
        app: wedding
    spec:
      serviceAccountName: wedding
      initContainers:
        - name: prepare-http-proxy-ca
          image: moby/buildkit:v0.8.1
          command:
            - sh
            - -c
            - |
              cp /ca_secret/ca.crt /usr/local/share/ca-certificates/http_proxy.crt
              update-ca-certificates
              cp -a /etc/ssl/certs/* /ca
          volumeMounts:
            - name: ca
              mountPath: "/ca"
            - name: ca-secret
              mountPath: /ca_secret
      containers:
        - name: wedding
          image: davedamoon/wedding:latest
          args:
            - --s3-endpoint=wedding-minio:9000
            - --s3-access-key-file=/secret/minio/MINIO_ACCESS_KEY
            - --s3-secret-key-file=/secret/minio/MINIO_SECRET_KEY
            - --s3-ssl=false
            - --s3-bucket=contexts
          env:
            - name: KEEP_FAILED_PODS
              value: "yes"
            - name: HTTP_PROXY
              value: http://wedding-docker-registry-proxy:3128
            - name: HTTPS_PROXY
              value: http://wedding-docker-registry-proxy:3128
            - name: NO_PROXY
              value: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.0/8,wedding-registry,wedding-minio
          ports:
            - name: wedding
              containerPort: 2376
          readinessProbe:
            httpGet:
              path: /_ping
              port: 2376
          volumeMounts:
            - name: minio
              mountPath: "/secret/minio"
              readOnly: true
            - name: ca
              mountPath: "/etc/ssl/certs/"
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "200Mi"
              cpu: "200m"
        - name: buildkit
          image: moby/buildkit:v0.8.1-rootless
          args:
            - --addr=tcp://127.0.0.1:1234
            - --oci-worker-no-process-sandbox
          env:
            - name: HTTP_PROXY
              value: http://wedding-docker-registry-proxy:3128
            - name: HTTPS_PROXY
              value: http://wedding-docker-registry-proxy:3128
            - name: NO_PROXY
              value: 10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.0/8,wedding-registry,wedding-minio
          volumeMounts:
            - name: buildkitd-config
              mountPath: "/home/user/.config/buildkit"
              readOnly: true
            - name: ca
              mountPath: "/etc/ssl/certs/"
          resources:
            requests:
              memory: "2148Mi"
              cpu: "500m"
            limits:
              memory: "2148Mi"
              cpu: "1000m"
      volumes:
        - name: minio
          secret:
            secretName: wedding-minio
        - name: buildkitd-config
          configMap:
            name: buildkitd-config
        - name: ca-secret
          secret:
            secretName: wedding-docker-registry-proxy-ca
        - name: ca
          emptyDir: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: wedding
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wedding
subjects:
- kind: ServiceAccount
  name: wedding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
# TODO create a custom set of permissions and avoid namespace admin role
#roleRef:
#  kind: Role
#  name: wedding
#  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wedding
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
